"""

Revision ID: 04ad1ab180df
Revises: ef475a5fc324
Create Date: 2022-10-18 20:55:58.848712

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '04ad1ab180df'
down_revision = 'ef475a5fc324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_unique_constraint(None, 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_table('categories')
    # ### end Alembic commands ###
