"""

Revision ID: 0ccd7b0ce634
Revises: 
Create Date: 2022-10-18 18:32:41.845562

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0ccd7b0ce634'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.VARCHAR(length=255), nullable=False),
        sa.Column('password', sa.VARCHAR(length=500), nullable=False),
        sa.Column('email', sa.VARCHAR(length=300), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
