"""

Revision ID: 0d9fdc76b43d
Revises: 64d5c838a390
Create Date: 2022-10-30 10:21:52.088633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0d9fdc76b43d'
down_revision = '64d5c838a390'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
