"""

Revision ID: 2e1cbb3e1d24
Revises: 5b3574e0454e
Create Date: 2022-10-26 19:32:12.114182

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e1cbb3e1d24'
down_revision = '5b3574e0454e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
