"""

Revision ID: 4611153c4f43
Revises: 1cbf6bf77de2
Create Date: 2022-10-20 10:58:47.161891

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4611153c4f43'
down_revision = '1cbf6bf77de2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'association',
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id']),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
