"""

Revision ID: 64d5c838a390
Revises: 2e1cbb3e1d24
Create Date: 2022-10-26 19:37:47.033255

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '64d5c838a390'
down_revision = '2e1cbb3e1d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
