"""

Revision ID: aeb3ba50f07e
Revises: 4611153c4f43
Create Date: 2022-10-20 11:05:54.816594

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aeb3ba50f07e'
down_revision = '4611153c4f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
